# fly.toml file generated for prologue-bot on 2022-11-27T12:19:58-06:00

app = "prologue-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

prompt_file_location = "Assets/Prompt Files"
